# Generated by Django 4.2.2 on 2023-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_type',
            field=models.IntegerField(blank=True, choices=[(0, 'CASH ON HAND'), (1, 'M-PESA SUPER'), (2, 'M-PESA MINOR'), (3, 'TIGO-PESA SUPER'), (4, 'TIGO-PESA MINOR'), (5, 'AIRTEL MONEY SUPER'), (6, 'AIRTEL MONEY MINOR'), (7, 'HALO PESA SUPER'), (8, 'HALO PESA MINOR'), (9, 'PBZ'), (10, 'NMB'), (11, 'CRDB')], default=None, null=True),
        ),
    ]
