# Generated by Django 4.2.2 on 2023-06-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='created_by',
            new_name='user',
        ),
    ]
