# Generated by Django 4.2.2 on 2023-06-14 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_business_branch_office_business_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='staff',
        ),
        migrations.AddField(
            model_name='office',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
