# Generated by Django 4.2.2 on 2023-06-22 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_office_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='staff',
            field=models.ManyToManyField(related_name='offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
