version: "3"

services:
  backend:
    restart: "always"
    build: .
    environment:
      IP: 127.0.0.1
    volumes:
      - .:/gcl
    command: bash -c "python manage.py runserver 0.0.0.0:7005"
    container_name: gcl
    image: gcl
    ports:
      - "7005:7005"
    networks:
      - webnet
networks:
  webnet:
